### ISSUE TITLE
Function basename is not safe in UTF-8

### ISSUE THREAD

**Issue by JimmDiGrizli** [alchemy-fr/Zippy#100]
PHP basename function is not safe in UTF-8 system, If the filename starts with an utf8 character, this character will be cut off. Example:

```php
 echo basename('Ängelholm');
// print  'ngelholm'
```

Might be worth define a _basename function and all basename function change to _basename.

**Comment by bburnichon** [comment]
Seems linked to https://bugs.php.net/bug.php?id=62119
