### ISSUE TITLE
Zip archive error

### ISSUE THREAD

**Issue by sannysoft** [alchemy-fr/Zippy#115]
Trying to get iterator for zip archive and it fails at ZipAdapter:120 when creating new member because $member[mtime] is not \DateTime

member = Array
(
    [location] => Invoice INVD063737 DD 19AUG16 RM10,567.82 - GO TRAVEL UN LIMITED.pdf
    [size] => 53273
    [mtime] => false
    [is_dir] => false
)

Error: 
Exception 'TypeError' with message 'Argument 5 passed to Alchemy\Zippy\Archive\Member::__construct() must be an instance of DateTime, boolean given, called in /private/var/www/jr_ota/vendor/alchemy/zippy/src/Adapter/ZipAdapter.php on line 126'

in /private/var/www/jr_ota/vendor/alchemy/zippy/src/Archive/Member.php:74

Stack trace:
#0 /private/var/www/jr_ota/vendor/alchemy/zippy/src/Adapter/ZipAdapter.php(126): Alchemy\Zippy\Archive\Member->__construct(Object(Alchemy\Zippy\Adapter\Resource\FileResource), Object(Alchemy\Zippy\Adapter\ZipAdapter), 'Invoice INVD063...', '53273', false, false)
#1 /private/var/www/jr_ota/vendor/alchemy/zippy/src/Adapter/AbstractAdapter.php(68): Alchemy\Zippy\Adapter\ZipAdapter->doListMembers(Object(Alchemy\Zippy\Adapter\Resource\FileResource))

**Comment by aztech-dev** [comment]
Can you specify your PHP version and used OS ?

Additionnally, you can check https://github.com/alchemy-fr/Zippy/issues/111 for some possible pointers on the source of the issue (it's most likely due to the date format used by your version of zip, which you can configure in Zippy)

**Comment by luizgabriel** [comment]
I'm having the same issue on my CentOS 6 running the Apache Server (httpd). 
(It works fine only on my windows machine as local development)

I'm running php 5.6 either on local and on server environment.

Please, fix this.
