### ISSUE TITLE
@info is not a valid tag in php doc

### ISSUE THREAD

**Issue by jducro** [alchemy-fr/Zippy#123]
The @info tags in some a the comments are causing error on Symfony:

https://github.com/alchemy-fr/Zippy/blob/master/src/Adapter/ZipExtensionAdapter.php#L335

> [Semantical Error] The annotation \"@info\" in method Alchemy\\Zippy\\Adapter\\ZipExtensionAdapter::checkReadability() was never imported. Did you maybe forget to add a \"use\" statement for this annotation?

They are not a part of the phpdoc [official tags](https://www.phpdoc.org/docs/latest/index.html)

Those should be regular comments without an @ prefix

**Comment by jducro** [comment]
https://github.com/alchemy-fr/Zippy/pull/124

**Comment by aztech-dev** [comment]
Fix is released as v0.4.6. Thanks
