### ISSUE TITLE
Request for a new release tag "0.4.10"

### ISSUE THREAD

**Issue by Hailong** [alchemy-fr/Zippy#150]
Can you please create a new release to make the recent changes in `master` branch available through composer?

**Comment by func0der** [comment]
https://github.com/alchemy-fr/Zippy/pull/156. Would love to have this merged in there, too. Updated the changelog accordingly :D

**Comment by func0der** [comment]
Version 1.0 released. Can we close this @Hailong ?

**Comment by Hailong** [comment]
Thank you. Let me close it now.
