### ISSUE TITLE
Split zippy?

### ISSUE THREAD

**Issue by temp** [alchemy-fr/Zippy#81]
I'm using zippy in a symfony project, and I really like it.
But it really bloats the required dependencies, it installs pimple and guzzle, although I'm neither using pimple for configuration, nor guzzle for the teleport-stuff.
I'd love to see smaller packages for zippy, with the main archive functionality in zippy, and for example zippy-teleport-guzzle as an addon for the guzzle-teleporter, and maybe zippy-pimple for the driver configuration. 
I didn't read into the teleporter-stuff very deeply, maybe even a package zippy-teleporter could be created, where the teleporter classes maintained? Don't know if the teleporter classes are used for regular archive handling...

I could provide a zippy-bundle for symfony integration, if someone is interested in this.

**Comment by aztech-dev** [comment]
:+1:

**Comment by davidkudera** [comment]
:+1:

**Comment by arrebucio** [comment]
:+1:

**Comment by aztech-dev** [comment]
Quick update, the Guzzle dependency is now optional (it has been moved to require-dev) and the library can work without it if you don't need to fetch remote archives.

As for the Pimple dependency, there's a work in progress to remove it completely from the library.

**Comment by arrebucio** [comment]
interesting, thanks!

**Comment by aztech-dev** [comment]
Closing this as Pimple is no longer required as of release 0.3.0

**Comment by temp** [comment]
Awesome, thank you! :+1:
