### ISSUE TITLE
Argument 5 passed to Alchemy\Zippy\Archive\Member::__construct() must be an instance of DateTime, boolean given

### ISSUE THREAD

**Issue by mztest** [alchemy-fr/Zippy#86]
// 785  2012-10-24 10:39  file
Class ZipOutputParser, line 53
\DateTime::createFromFormat("Y-m-d H:i", $chunks[2]);

I am trying to get  the archive members, and see this error.
When I tracked the error, I noticed the command "unzip -l" returned the different date time format.

Centos: 10-23-2015 20:56
Mac 10.11:  10-23-15 20:56

How can I fix it or change it?

Thanks a lot.

**Comment by GoktugOzturk** [comment]
Our code works on different systems (windows, macos, linux).
Everytime i use Zippy, calling a static parameter with different parameters for each platform doesn't look pretty. 
Should we create an identifier function which tries to identify the operating system and sets default time format for that platform?

I would create this function if needed.
