### ISSUE TITLE
No adapter available for tar.gz on this platform

### ISSUE THREAD

**Issue by burnet** [alchemy-fr/Zippy#95]
Hi,
I get an `NoAdapterOnPlatformException` when I attempt to create a tar.gz archive, not sure what I'm missing:

````
    $zippy = Zippy::load();
    $zippy->create('test.tar.gz', 'testfiles/');
````

tar also fails, *No adapter available for tar on this platform*
````
    $zippy = Zippy::load();
    $zippy->create('test.tar', 'testfiles/');
````

Creating a zip archive does succeed, however.

Zippy 0.3.2 on Ubuntu 14.04.3 LTS

Trace:
````

Fatal error:  Uncaught exception 'Alchemy\Zippy\Exception\NoAdapterOnPlatformException' with message 'No adapter available for tar.gz on this platform' in /var/www/zippy-test/vendor/alchemy/zippy/src/Zippy.php:160
Stack trace:
#0 /var/www/zippy-test/vendor/alchemy/zippy/src/Zippy.php(67): Alchemy\Zippy\Zippy->getAdapterFor('tar.gz')
#1 /var/www/zippy-test/web/index.php(18): Alchemy\Zippy\Zippy->create('test.tar.gz', 'testfiles/')
#2 {main}

Next exception 'Alchemy\Zippy\Exception\RuntimeException' with message 'Unable to create archive' in /var/www/zippy-test/vendor/alchemy/zippy/src/Zippy.php:70
Stack trace:
#0 /var/www/zippy-test/web/index.php(18): Alchemy\Zippy\Zippy->create('test.tar.gz', 'testfiles/')
#1 {main}
  thrown in /var/www/zippy-test/vendor/alchemy/zippy/src/Zippy.php on line 70
````

**Comment by aztech-dev** [comment]
Can you give me the output of the following shell commands :

```
tar --version
gnutar --version
```

Thanks

**Comment by burnet** [comment]
Thanks for the fast reply.

````
$ tar --version
tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
````
````
$ gnutar --version
gnutar: command not found
````

**Comment by aztech-dev** [comment]
Also, are you running the script from a web server or in the console ?

**Comment by aztech-dev** [comment]
And what's the output of `which tar` ?

**Comment by burnet** [comment]
The code in the initial post is being run from the web server.

````
$ which tar
/bin/tar
````

**Comment by aztech-dev** [comment]
Can you try running your sample code from the console directlly ? If it works via the console, it's most likely that the user running your webserver (probably www-data) does not have access/execute rights on the tar binary.

**Comment by burnet** [comment]
Hi,

Thanks for your help and prompt replies! It does seem to work from the console so I think you're right.

Never had to deal with this before though, and /bin/tar seems to have execute permissions for everybody. Any advice for letting www-data execute this?

Thanks!

**Comment by aztech-dev** [comment]
That's a bit hard to say actually. You may want to make sure that PHP's safe-mode is not enabled in your webserver's config (the Apache or Nginx specific PHP ini file). Other than that, not sure I can help you much with that issue.

**Comment by burnet** [comment]
So I've solved the issue and want to post my findings for future reference.

PHP's `PATH` environment variable was empty. On my setup at least, PHP-FPM's configuration does not pass these through automatically, the lines in its config were commented out by default:
````
;env[HOSTNAME] = $HOSTNAME
;env[PATH] = /usr/local/bin:/usr/bin:/bin
;env[TMP] = /tmp
;env[TMPDIR] = /tmp
;env[TEMP] = /tmp
````

So when Zippy attempts to find a binary (via `Symfony\Component\Process\ExecutableFinder`) it was actually only trying `/gnutar`, `/tar` and `/bsdtar` - none of which exist.

Creating ZIP archives would have failed here too, but it looks like Zippy can fall back to PHP's /ZipArchive in this case.
